#' handcoder_app: App to classify text snippets
#'
#' `handcoder_app` is an internal function to `handcode`. It provides a Shiny-App that allows users to click through different snippets of text and classify them manually according to predefined categories.
#'
#' @param a A list containing all relevant information for the app to function. The list will be automatically generated by `data_for_app`.
#'
# Importing dependencies with roxygen2
#' @import shiny
#' @importFrom shinyWidgets progressBar
#' @importFrom shinyWidgets updateProgressBar
#' @return The Shiny-App returns a data frame with the coded variables.


handcoder_app <- function(a) {
  shinyApp(
    ui = shiny::fluidPage(

      # Generate html-class that hides output
      shiny::tags$head(
        shiny::tags$style(
          shiny::HTML(".hide-checkbox {display: none;}"),
        )
      ),

      shiny::tags$head(
        shiny::tags$style(
          shiny::HTML("
        /* Increase spacing after htmlOutput('statement') */
        .statement-output {
          margin-bottom: 20px;
        }

        /* Add box around htmlOutput('statement') */
        .statement-output {
          border: 1px solid #ccc;
          padding: 10px;
        }
      ")
        )
      ),


      # Title
      shiny::titlePanel("handcodeR Text Annotation App"),

      # Main Panel
      shiny::mainPanel(

        # Text Statement
        shiny::fluidRow(
          shiny::column(width = floor(12/(a$compare+1)),
                        shiny::h3("Statement:"),
                        shiny::div(
                          shiny::htmlOutput("statement"),
                          class = "statement-output"),
                        shiny::HTML("<br>")
          ),
          # Invisible checkbox for optional comparison
          shiny::div(shiny::checkboxInput(
            "compare",
            "Add second text",
            value = a$compare),
            class = "hide-checkbox"
          ),
          shiny::conditionalPanel(
            condition = "input.compare",
            shiny::column(width = floor(12/(a$compare+1)),
                          shiny::h3("Comparison:"),
                          shiny::div(
                            shiny::htmlOutput("comparison"),
                            class = "statement-output"),
                          shiny::HTML("<br>")
            ))),

        # Coding Categories
        shiny::fluidRow(
          shiny::column(width = floor(12/length(a$classifications)),
                        shiny::radioButtons(
                          "code1",
                          names(a$classifications)[1],
                          choiceNames = button_output(a$classifications, 1),
                          choiceValues = button_output(a$classifications, 1, names = TRUE),
                          selected = ""
                        )
          ),
          # Invisible checkbox for optional categories
          shiny::div(shiny::checkboxInput(
            "add2",
            "Add second classification",
            value = length(a$classifications)>1),
            class = "hide-checkbox"
          ),
          shiny::conditionalPanel(
            condition = "input.add2",
            shiny::column(width = floor(12/length(a$classifications)),
                          shiny::radioButtons(
                            "code2",
                            try(names(a$classifications)[2], silent = TRUE),
                            selected = "",
                            choiceNames = button_output(a$classifications, 2),
                            choiceValues = button_output(a$classifications, 2, names = TRUE),
                          )
            )),
          shiny::div(shiny::checkboxInput(
            "add3",
            "Add third classification",
            value = length(a$classifications)>2),
            class = "hide-checkbox"
          ),
          shiny::conditionalPanel(
            condition = "input.add3",
            shiny::column(width = floor(12/length(a$classifications)),
                          shiny::radioButtons(
                            "code3",
                            try(names(a$classifications)[3], silent = TRUE),
                            selected = "",
                            choiceNames = button_output(a$classifications, 3),
                            choiceValues = button_output(a$classifications, 3, names = TRUE),
                          )
            )),
          shiny::div(shiny::checkboxInput(
            "add4",
            "Add fourth classification",
            value = length(a$classifications)>3),
            class = "hide-checkbox"
          ),
          shiny::conditionalPanel(
            condition = "input.add4",
            shiny::column(width = floor(12/length(a$classifications)),
                          shiny::radioButtons(
                            "code4",
                            try(names(a$classifications)[4], silent = TRUE),
                            selected = "",
                            choiceNames = button_output(a$classifications, 4),
                            choiceValues = button_output(a$classifications, 4, names = TRUE),
                          )
            )),
          shiny::div(shiny::checkboxInput(
            "add5",
            "Add fifth classification",
            value = length(a$classifications)>4),
            class = "hide-checkbox"
          ),
          shiny::conditionalPanel(
            condition = "input.add5",
            shiny::column(width = floor(12/length(a$classifications)),
                          shiny::radioButtons(
                            "code5",
                            try(names(a$classifications)[5], silent = TRUE),
                            selected = "",
                            choiceNames = button_output(a$classifications, 5),
                            choiceValues = button_output(a$classifications, 5, names = TRUE),
                          )
            )),
          shiny::div(shiny::checkboxInput(
            "add6",
            "Add sixth classification",
            value = length(a$classifications)>5),
            class = "hide-checkbox"
          ),
          shiny::conditionalPanel(
            condition = "input.add6",
            shiny::column(width = floor(12/length(a$classifications)),
                          shiny::radioButtons(
                            "code6",
                            try(names(a$classifications)[6], silent = TRUE),
                            selected = "",
                            choiceNames = button_output(a$classifications, 6),
                            choiceValues = button_output(a$classifications, 6, names = TRUE),
                          )
            ))
        ),

        # Space and Enter to press next and previous
        shiny::tags$head(
          shiny::tags$script(
            '$(document).on("keyup", function (e) {
          if ( e.which == 32 ) document.getElementById("previouspage").click();
          if ( e.which == 13 ) document.getElementById("nextpage").click();
        });'
          )
        ),
        shiny::HTML("<br><br>"),



        # Buttons for next and previous
        shiny::actionButton("previouspage","Previous", class = "btn btn-primary",
                            style = "position: absolute; bottom: 60px; right: 90px;",
                            icon = shiny::icon("backward")),

        shiny::actionButton("nextpage", "Next", class = "btn btn-primary",
                            style = "position: absolute; bottom: 60px; right: 10px;",
                            icon = shiny::icon("forward")),

        # Button for save and exit
        shiny::actionButton("save", "Save and exit", class = "btn btn-primary",
                            style = "position: absolute; bottom: 60px; left: 10px;",
                            icon = shiny::icon("floppy-disk")),

        # Help Text
        shiny::helpText(
          sprintf(
            'Use Space and Enter keys to go to "%s" or "%s" page, respectively.',
            "Previous",
            "Next"
          )
        ),

        # Progress bar
        shinyWidgets::progressBar(
          id = "progress",
          value = a$start_app,
          total = nrow(a$data_app),
          size = "xxs"
        ),
        tags$head(tags$style(HTML('.progress-number {position: absolute; bottom: -10px; right: -10px; color: black;}'))),
        tags$head(tags$style(HTML('.progress {height: 6px; margin-top: -21px;}')))
      )
    ),
    server = function(input, output, session) {

      # Initialize reactiveValues
      values <- shiny::reactiveValues(
        # Set counter to start
        counter = a$start_app,

        # Initialize coding as existing classification
        code1 = a$container[,1],
        code2 = a$container[,2],
        code3 = a$container[,3],
        code4 = a$container[,4],
        code5 = a$container[,5],
        code6 = a$container[,6]
      )

      # Initialize radioButtons
      observe({
        shiny::updateRadioButtons(session, "code1", selected = values$code1[values$counter])
        shiny::updateRadioButtons(session, "code2", selected = values$code2[values$counter])
        shiny::updateRadioButtons(session, "code3", selected = values$code3[values$counter])
        shiny::updateRadioButtons(session, "code4", selected = values$code4[values$counter])
        shiny::updateRadioButtons(session, "code5", selected = values$code5[values$counter])
        shiny::updateRadioButtons(session, "code6", selected = values$code6[values$counter])
      })


      # Behaviour when previous is clicked
      shiny::observeEvent(input$previouspage, {

        # Save current coding
        values$code1[values$counter] <- input$code1
        try(values$code2[values$counter] <- input$code2, silent = TRUE)
        try(values$code3[values$counter] <- input$code3, silent = TRUE)
        try(values$code4[values$counter] <- input$code4, silent = TRUE)
        try(values$code5[values$counter] <- input$code5, silent = TRUE)
        try(values$code6[values$counter] <- input$code6, silent = TRUE)

        # Update the counter value by substracting 1 but only if page is bigger 1
        if (values$counter > 1) {
          values$counter <- values$counter - 1
        }

        # Set the selected value of radioButtons to "" or already coded category
        shiny::updateRadioButtons(session, "code1", selected = ifelse(is.na(values$code1[values$counter]), "", values$code1[values$counter]))
        shiny::updateRadioButtons(session, "code2", selected = ifelse(is.na(values$code2[values$counter]), "", values$code2[values$counter]))
        shiny::updateRadioButtons(session, "code3", selected = ifelse(is.na(values$code3[values$counter]), "", values$code3[values$counter]))
        shiny::updateRadioButtons(session, "code4", selected = ifelse(is.na(values$code4[values$counter]), "", values$code4[values$counter]))
        shiny::updateRadioButtons(session, "code5", selected = ifelse(is.na(values$code5[values$counter]), "", values$code5[values$counter]))
        shiny::updateRadioButtons(session, "code6", selected = ifelse(is.na(values$code6[values$counter]), "", values$code6[values$counter]))

        # Update progress bar
        shinyWidgets::updateProgressBar(id = "progress", value = values$counter, total = nrow(a$data_app))
      })

      # Behaviour when next is clicked
      shiny::observeEvent(input$nextpage, {

        # Save current coding
        values$code1[values$counter] <- input$code1
        try(values$code2[values$counter] <- input$code2, silent = TRUE)
        try(values$code3[values$counter] <- input$code3, silent = TRUE)
        try(values$code4[values$counter] <- input$code4, silent = TRUE)
        try(values$code5[values$counter] <- input$code5, silent = TRUE)
        try(values$code6[values$counter] <- input$code6, silent = TRUE)

        # If max pages reached, save and exit
        if (values$counter == length(a$data_app$texts)) {

          # Stop the Shiny-App and output data frame
          shiny::stopApp(invisible(gen_output(a$data_app, values)))
        }

        # Update the counter value by adding 1
        values$counter <- values$counter + 1

        # Set the selected value of radioButtons to "" or already coded category
        shiny::updateRadioButtons(session, "code1", selected = ifelse(is.na(values$code1[values$counter]), "", values$code1[values$counter]))
        shiny::updateRadioButtons(session, "code2", selected = ifelse(is.na(values$code2[values$counter]), "", values$code2[values$counter]))
        shiny::updateRadioButtons(session, "code3", selected = ifelse(is.na(values$code3[values$counter]), "", values$code3[values$counter]))
        shiny::updateRadioButtons(session, "code4", selected = ifelse(is.na(values$code4[values$counter]), "", values$code4[values$counter]))
        shiny::updateRadioButtons(session, "code5", selected = ifelse(is.na(values$code5[values$counter]), "", values$code5[values$counter]))
        shiny::updateRadioButtons(session, "code6", selected = ifelse(is.na(values$code6[values$counter]), "", values$code6[values$counter]))

        shinyWidgets::updateProgressBar(id = "progress", value = values$counter, total = nrow(a$data_app))
      })

      # Update text displayed
      if(a$context_app){
        current_text <- reactive({
          paste0("<font color =\"#C0C0C0\">", a$data_app$before[values$counter], "</font> <b>", a$data_app$texts[values$counter], "</b> <font color =\"#C0C0C0\">", a$data_app$after[values$counter], "</font>")
        })} else {
          current_text <- reactive({
            a$data_app$texts[values$counter]
          })
        }

      output$statement <- renderText({
        current_text()
      })

      # Update comparison displayed
      if(a$compare){
        if(a$context_app){
          current_comparison <- reactive({
            paste0("<font color =\"#C0C0C0\">", a$data_app$before_comparison[values$counter], "</font> <b>", a$data_app$comparison[values$counter], "</b> <font color =\"#C0C0C0\">", a$data_app$after_comparison[values$counter], "</font>")
          })} else {
            current_comparison <- reactive({
              a$data_app$comparison[values$counter]
            })
          }
        output$comparison <- renderText({
          current_comparison()
        })
      } else {
        output$comparison <- renderText({
          current_text()
        })
      }


      # Behaviour when save is clicked
      shiny::observeEvent(input$save, {

        # Save current coding
        values$code1[values$counter] <- input$code1
        try(values$code2[values$counter] <- input$code2, silent = TRUE)
        try(values$code3[values$counter] <- input$code3, silent = TRUE)
        try(values$code4[values$counter] <- input$code4, silent = TRUE)
        try(values$code5[values$counter] <- input$code5, silent = TRUE)
        try(values$code6[values$counter] <- input$code6, silent = TRUE)

        # Stop the Shiny-App and output data frame
        shiny::stopApp(invisible(gen_output(a$data_app, values)))
      })

    }
  )
}


#' button_output: Formatting of output for shiny::radioButtons
#'
#' `button_output` is an internal function to `handcode`. It works within the Shiny-App `handcoder_app` to format the look of the shiny::radioButtons.
#' @param classification Classification list obtained as list item from `data_for_app`
#' @param button Numerical value indicating for which button names and labels should be returned
#' @param names Logical value indicating whether the function is supposed to return a formatted list of labels or a vector of names for use in radioButtons.
#' @return Depending on the logical names input, the function returns a list of HTML formatted labels or the list of category names for the display of the radioButtons in the Shiny-App.

button_output <- function(classification, button, names = FALSE) {
  # If
  if(button <= length(classification)){

    class <- classification[[button]]

    if(!names) {
      class <- as.list(class)

      # Pick all Missings
      log <- grepl("\\_(.)*\\_", class)

      # Last Missing
      marg <- max(which(log), warning = FALSE)

      # Missings without _
      no_ <- gsub("\\_", "", class)

      # Apply HTML to all missings
      class[log] <- lapply(no_[log], function(x) shiny::HTML(paste0("<p style = 'color:#C0C0C0'>", x, "</p>")))
      class[marg] <- lapply(no_[marg], function(x) shiny::HTML(paste0("<p style = 'color:#C0C0C0; margin-bottom:15pt'>", x, "</p>")))
    }
  } else {
    class <- c("")
  }

  return(class)
}


#' gen_output: Combine data and values of Shiny-App to output
#'
#' `gen_output` is an internal function to `handcode`. It works within the Shiny-App `handcoder_app` to prepare the output data frame.
#' @param data The data frame initially passed to `handcoder_app` within a.
#' @param values The values generated by the server of the `handcoder_app`.
#' @return The function returns a data frame with the coded variables.

gen_output <- function(data, values){

  # Generate final data frame to be displayed as output
  if("comparison" %in% names(data)) {
    final <- data.frame(id = data$id, texts = data$texts, comparison = data$comparison,
                        kat1 = values$code1,
                        kat2 = values$code2,
                        kat3 = values$code3,
                        kat4 = values$code4,
                        kat5 = values$code5,
                        kat6 = values$code6)
  } else {
    final <- data.frame(id = data$id, texts = data$texts,
                        kat1 = values$code1,
                        kat2 = values$code2,
                        kat3 = values$code3,
                        kat4 = values$code4,
                        kat5 = values$code5,
                        kat6 = values$code6)
  }


  # Reduce to size of original data frame
  if("comparison" %in% names(data)){
    final <- final[, seq_len(ncol(data)-4)]
  } else {
    final <- final[,seq_len(ncol(data)-2)]
  }

  # Take names from original data frame
  if("comparison" %in% names(data)){
    names(final) <- names(data)[-c(2,3, 4, 5)]
  } else {
    names(final) <- names(data)[-c(2,3)]
  }

  # Make sure all NA is saved as ""
  final[is.na(final)] <- ""

  # Reorder output
  final <- final[order(final$id),]

  # Delete id
  final <- final[,-1]
  rownames(final) <- NULL

  # Return
  return(final)
}


#' character_to_data: Transform text vector and arg_list to data frame.
#'
#' `character_to_data` is an internal function to `handcode`. It takes a character vector of texts as well as an arg_list of named character vectors as inputs and returns a data frame which can be used as input to `data_for_app`.
#' @param data A character vector of texts which has been given as data input to `handcode`.
#' @param comparison A character vector of texts to compare against data which has been given as comparison input to `handcde`.
#' @param arg_list A list of additional arguments which have been given as input to `handcode`. These must be named character vectors of categories that will be used to annotate the given texts.
#' @param missing A character vector of values that are displayed as missing values in the App. In the return data, these missing will be saved with an additional "_" as prefix and suffix.
#' @return The function returns a data frame in the format of the output data frame that can be processed by the handcode() function.

character_to_data <- function(data, comparison = NULL, arg_list, missing) {

  output <- data.frame(matrix(factor(""), nrow = length(data), ncol = length(arg_list)))

  # Name variables according to arg_list
  names(output) <- names(arg_list)

  # Add _ to missing
  missing <- paste0("_", missing, "_")

  # For every categorisation, set levels of factor
  for (i in seq_along(arg_list)){
    output[,i] <- factor("", levels = c("", missing, arg_list[[i]]))
  }

  # Paste texts object to data frame
  if(is.null(comparison)){
    data <- data.frame(texts = data, output)
  } else {
    data <- data.frame(texts = data, comparison = comparison, output)
  }

  return(data)

}


#' data_for_app: Prepare inputs for Shiny-App
#'
#' `data_for_app` is an internal function to `handcode`. It takes the inputs data, start, randomize and context to generate a list of inputs which can then be passed to `handcoder_app`.
#' @param data A data frame that has been prepared by `character_to_data` or that has previously already been returned from `handcode`.
#' @param start The value that has been given as start value to `handcode`.
#' @param randomize The logical value that has been given as randomize to `handcode`.
#' @param context The logical value that has been given as context to `handcode`.
#' @param pre Optional vector of texts that come before each respective text to be coded.
#' @param post Optional vector of texts that come after each respective text to be coded.
#' @param comparison_pre Optional vector of texts that come before each respective comparison text to be coded.
#' @param comparison_post Optional vector of texts that come after each respective comparison text to be coded.
#' @return The function returns a list of inputs needed within the Shiny-App.

data_for_app <- function(data, start, randomize, context, pre = NULL, post = NULL, comparison_pre = NULL, comparison_post = NULL) {

  a <- list()

  if(is.null(pre) & is.null(post)){
    # Add context to data frame
    data <- data.frame(before = c("", data$texts[seq_len(nrow(data)-1)]), after = c(data$texts[seq(2, nrow(data))], ""), data)
  } else {
    data <- data.frame(before = pre, after = post, data)
  }

  # If comparison in data, but comparison_pre and comparison_post are NULL, add context to data.frame
  if("comparison" %in% names(data)) {
    if(is.null(comparison_pre) & is.null(comparison_post)){
      # Add context to data frame
      data <- data.frame(before_comparison = c("", data$comparison[seq_len(nrow(data)-1)]), after_comparison = c(data$comparison[seq(2, nrow(data))], ""), data)
    } else {
      data <- data.frame(before_comparison = comparison_pre, after_comparison = comparison_post, data)
    }
  }

  # Add id variable to data
  data <- cbind(id = seq_len(nrow(data)), data)

  # if start == "all_empty", reorder data
  if(start == "all_empty"){
    data <- data[order(rowSums(data.frame(data[,!names(data) %in% c("id", "texts", "comparison", "before", "after", "before_comparison", "after_comparison")], helper = "A") == "")>0), ]
  }


  # Set start to first empty row of data
  if(start %in% c("first_empty", "all_empty")){
    start <- min(seq_len(nrow(data))[rowSums(data.frame(data[,!names(data) %in% c("id", "texts", "comparison", "before", "after", "before_comparison", "after_comparison")], helper = "A") == "")>0])
  }

  # If randomize is TRUE, randomize order after start value
  # c(1:start-1, ...) is intentionally without parantheses due to different behaviour of c(1:1) and c(1:0)
  if(randomize & start < nrow(data)){
    data <- data[c(1:start-1, sample(start:nrow(data), nrow(data)-(start-1))),]
  }

  # List to store classifications and their categories
  classifications <- vector("list", length = sum(!names(data) %in% c("id", "texts", "comparison", "before", "after", "before_comparison", "after_comparison")))

  # Name list
  names(classifications) <- names(data)[!names(data) %in% c("id", "texts", "comparison", "before", "after", "before_comparison", "after_comparison")]

  # Fill with categories
  for (i in seq_along(classifications)) {
    classifications[[i]] <- levels(data[,names(classifications)[i]])
  }

  # Initialize container for classification
  container <- data.frame(kat1 = factor(rep("", nrow(data))), kat2 = factor(""), kat3 = factor(""), kat4 = factor(""), kat5 = factor(""), kat6 = factor(""))

  for (i in seq_along(classifications)){
    container[,i] <- data[,names(classifications)[i]]
    names(container)[i] <- names(classifications)[[i]]
    levels(container[,i]) <- c(classifications[[i]])
  }

  # Pass to app
  a$container <- container
  a$data_app <- data
  a$start_app <- start
  a$classifications <- classifications
  a$context_app <- context
  a$compare <- "comparison" %in% names(data)


  return(a)

}


#' handcode: Classifying text into pre-defined categories.
#'
#' `handcode()` opens an interactive Shiny app that allows you to classify strings of text into predefined categories. You can annotate between one and six variables at a time. The function returns an updated data frame containing your annotated classifications.
#'
#' @param data A character vector of texts to annotate, or a data frame previously returned by `handcode()`.
#' @param ... Between 1 and 6 named character vectors defining annotation variables and their categories.
#'   These are only required when `data` is a new character vector of texts (not a data frame returned by `handcode()`).
#' @param start A single value indicating where to begin hand coding.
#'   - If numeric, coding will start at the specified row number.
#'   - `"first_empty"`: automatically start at the first row that is not fully annotated (i.e., at least one classification column is still empty).
#'   - `"all_empty"`: display all rows that are not fully annotated for coding.
#' @param randomize A single logical value (`TRUE` or `FALSE`) indicating whether to randomize the order in which texts are displayed to the coder.
#' @param context A single logical value (`TRUE` or `FALSE`) indicating whether to display the previous and next texts alongside the current text being coded.
#'   When `TRUE`, the surrounding texts are shown in light gray.
#'   This is particularly useful when annotating individual sentences within a larger document.
#' @param missing A character vector of values to be treated as missing across all annotation vectors.
#'   In the returned data, these missing values are marked by adding an underscore ('_') at the beginning and end of each value.
#' @param pre Optional character vector of custom texts to display as the preceding context for each text in `data`.
#'   These texts are shown only if `context = TRUE`.
#'   This is useful when the texts in `data` do not form a continuous sequence.
#' @param post Optional character vector of custom texts to display as the following context for each text in `data`.
#'   These texts are shown only if `context = TRUE`.
#'   This is useful when the texts in `data` do not form a continuous sequence.
#' @param comparison Optional. A character vector of texts to compare against the texts in `data`.
#'   This argument is typically used on the first run; when resuming from a previous `handcode()` output, the comparison column in `data` will be used automatically.
#' @param comparison_pre Optional character vector of custom texts to display as the preceding context for each text in `comparison`.
#'   These texts are shown only if `context = TRUE`.
#'   This is useful when the texts in `comparison` do not form a continuous sequence.
#' @param comparison_post Optional character vector of custom texts to display as the following context for each text in `comparison`.
#'   These texts are shown only if `context = TRUE`.
#'   This is useful when the texts in `comparison` do not form a continuous sequence.
#'
#' @return A data frame containing all annotations made in the Shiny app.
#'   Each row corresponds to a text from the input `data` (or `comparison`), and each annotation variable is stored as a factor column.

#' @examplesIf interactive()
#' reviews <- c("Good Quality Dog Food",
#'              "Not as Advertised",
#'              "Delight says it all",
#'              "Great! Just as good as the expensive brands")
#' annotated <- handcode(reviews, evaluation = c("positive", "negative"))
#'
#' @examplesIf interactive()
#' # Original sentences
#' sentences <- c(
#'   "The weather today is sunny and warm.",
#'   "I love eating chocolate cake.",
#'   "She enjoys going for a run every morning.",
#'   "This movie was absolutely fantastic."
#' )
#'
#' # Redacted/reworded versions to compare
#' redacted_sentences <- c(
#'   "Today's weather is sunny and warm.",
#'   "I enjoy the taste of chocolate.",
#'   "She likes jogging each morning.",
#'   "The film was really great."
#' )
#'
#' # Handcode sentences to see if meaning changed
#' annotated <- handcode(
#'   data = sentences,
#'   comparison = redacted_sentences,
#'   meaning_change = c("unchanged", "changed")
#' )

#'
#'
# Importing dependencies with roxygen2
#' @import shiny
#' @importFrom shinyWidgets progressBar
#' @importFrom shinyWidgets updateProgressBar
#'
# Export function
#' @export


handcode <- function(data, ... , start = "all_empty", randomize = FALSE, context = FALSE, missing = c("Not applicable"), pre = NULL, post = NULL, comparison = NULL, comparison_pre = NULL, comparison_post = NULL) {

  # Initialize ...
  arg_list <- list(...)

  # Checks and datahandling for data input ----------------------------------

  # Check if data is either data frame or character vector of texts
  if(!is.data.frame(data) & !is.character(data)) stop("Invalid 'data' argument: 'data' must be either a character vector of texts or a data frame returned from a previous handcode() session.")


  # Check comparison input
  if (!is.null(comparison)) {
    if (is.data.frame(data)) {
      # If data is from previous run, ignore comparison
      if (!"comparison" %in% names(data)) warning("'comparison' was ignored because 'data' was supplied as a data frame.
If you intended to start a new comparison annotation, please provide raw text vectors instead of a previous handcode() output.")
      if ("comparison" %in% names(data)) warning("'comparison' was ignored because 'data' already includes comparison information from a previous handcode() run.")

      comparison <- NULL

    } else {
      # Check type
      if (!is.character(comparison)) {
        stop("Invalid 'comparison' argument: 'comparison' must be a character vector.")
      }
      # Check length
      if (length(comparison) != length(data)) {
        stop("Invalid 'comparison' argument: 'comparison' must have the same length as 'data' (", nrow(data), "), but length = ", length(comparison), ".")
      }
    }
  }

  # Checks and data handling if data is character vector
  if(is.character(data)){

    # Check if items in arg_list are named vectors
    if(!all(vapply(arg_list, is.character, logical(1))) || !all(vapply(arg_list, is.vector, logical(1)))) {
      stop("Arguments passed in '...' must be named character vectors (e.g., category = c('a','b')).")
    }

    # Check that there are between 1 and 6 named character vectors given
    if(length(arg_list) < 1 || length(arg_list) > 6) {
      stop("You must supply between 1 and 6 named character vectors of annotation categories when providing raw text data.")
    }

    # Check if "" is in list of categories
    if(any(vapply(arg_list, function(x) "" %in% x, logical(1)))) stop('The empty string "" cannot be used as a category in any annotation vector.')


    # Missing is character vector
    if(!is.character(missing)) stop("Invalid 'missing' argument. Provide a character vector of values to be treated as missing in all annotation vectors.")

    # Check if duplicates between missing and categories
    if(any(vapply(arg_list, function(x) missing %in% x, logical(length(missing))))) stop("Invalid input: some category values are also listed in 'missing'. Please remove them from one of the arguments.")

    # Check for duplicate categories
    for (i in seq_along(arg_list)) {
      if(length(unique(arg_list[[i]]))<length(arg_list[[i]])) stop("Duplicate categories detected. Ensure each annotation vector contains only unique values.")
    }

    # Data handling
    data <- character_to_data(data, comparison, arg_list, missing)

  }

  # Checks -----------------------------------------------------------------------

  # Check if first column of data is texts and character
  if(names(data)[1] != "texts" | !is.character(data[,1]) ) stop("Invalid 'data'. Only a data frame returned from a previous handcode() run is allowed. The first column must be named 'texts' and contain character values.", "Alternatively provide a character vector of texts to annotate.")

  # Check if column comparison exists and is character
  if (is.data.frame(data) && "comparison" %in% names(data)) {
    # Check that the comparison column is character
    if (!is.character(data$comparison)) {
      stop("'comparison' column in the provided data frame must be of type character. ",
           "Only data frames returned by a previous handcode() run are allowed.")
    }
  }


  # Check if pre and post exist in data frame. If yes, save them as individual vectors and remove them from data
  if(is.data.frame(data) & "pre" %in% names(data) & "post" %in% names(data)) {
    pre <- data$pre
    post <- data$post
    data <- data[,!names(data) %in% c("pre", "post")]
  }

  # Check if pre and post exist in data frame. If yes, save them as individual vectors and remove them from data
  if(is.data.frame(data) & "comparison_pre" %in% names(data) & "comparison_post" %in% names(data)) {
    comparison_pre <- data$pre
    comparison_post <- data$post
    data <- data[,!names(data) %in% c("comparison_pre", "comparison_post")]
  }

  # Check if there are min 1 and  max 6 classification variables
  if (sum(!names(data) %in% c("texts", "comparison")) < 1 || sum(!names(data) %in% c("texts", "comparison")) > 6) stop("Invalid input: provide between 1 and 6 classification variables. ", "Only the remaining annotation columns after excluding 'texts', 'comparison', and pre/post columns are counted.")

  # Check if all columns that are not texts or comparison are factors
  if(names(data)[2] == "comparison") {
    if(!all(vapply(data[, -c(1,2)], is.factor, FUN.VALUE = logical(1)))) stop("Invalid data: all remaining annotation columns must be factors. ", "Ensure you provide a data frame returned from a previous handcode() run.")
  } else {
    if(!all(vapply(data[, -1], is.factor, FUN.VALUE = logical(1)))) stop("Invalid data: all remaining annotation columns must be factors. ", "Ensure you provide a data frame returned from a previous handcode() run.")
  }

  # check if start is a single value
  if(length(start) > 1) stop("Invalid 'start' value: provide a single numeric value or one of 'first_empty' / 'all_empty'.")

  # Check if start is numeric or "first_empty"
  if(!is.numeric(start) & !start%in%c("first_empty", "all_empty")) stop("Invalid 'start' value: provide a single numeric value or one of 'first_empty' / 'all_empty'.")

  # Check if there is uncoded data
  if(!any(data[,!names(data) %in% c("texts", "comparison")] == "")) stop("All classification columns are filled. At least one empty annotation is required to continue.")

  # Check if randomize is single value
  if(length(randomize)>1) stop("Invalid 'randomize' argument: provide a single TRUE or FALSE value.")

  # Check if randomize is logical
  if(!is.logical(randomize)) stop("Invalid 'randomize' argument: provide a single TRUE or FALSE value.")

  # Check if context is single value
  if(length(context)>1) stop("Invalid 'context' argument: provide a single TRUE or FALSE value.")

  # Check if context is logical
  if(!is.logical(context)) stop("Invalid 'context' argument: provide a single TRUE or FALSE value.")

  # Check if pre is null or character
  if(!is.null(pre) & !is.character(pre)) stop("Invalid 'pre' argument: must be a character vector.")

  # Check if post is null or character
  if(!is.null(post) & !is.character(post)) stop("Invalid 'post' argument: must be a character vector.")

  # If pre is given, check if correct length
  if(is.character(pre) & length(pre) != nrow(data)) stop("'pre' must have the same length as 'data' (", nrow(data), "), but length = ", length(pre), ".")

  # If post is given, check if correct length
  if(is.character(post) & length(post) != nrow(data)) stop("'post' must have the same length as 'data' (", nrow(data), "), but length = ", length(post), ".")

  # If only one of pre and post is given, set up the other one
  if(!is.null(pre) & is.null(post)) post <- rep("", nrow(data))
  if(!is.null(post) & is.null(pre)) pre <- rep("", nrow(data))



  # Check if comparison_pre is null or character
  if(!is.null(comparison_pre) & !is.character(comparison_pre)) stop("Invalid 'comparison_pre' argument: must be a character vector.")

  # Check if comparison_post is null or character
  if(!is.null(comparison_post) & !is.character(comparison_post)) stop("Invalid 'comparison_post' argument: must be a character vector.")

  # If pre is given, check if correct length
  if(is.character(comparison_pre) & length(comparison_pre) != nrow(data)) stop("'comparison_pre' must have the same length as 'data' (", nrow(data), "), but length = ", length(comparison_pre), ".")

  # If post is given, check if correct length
  if(is.character(comparison_post) & length(comparison_post) != nrow(data)) stop("'comparison_post' must have the same length as 'data' (", nrow(data), "), but length = ", length(comparison_post), ".")

  # If only one of pre and post is given, set up the other one
  if(!is.null(comparison_pre) & is.null(comparison_post)) comparison_post <- rep("", nrow(data))
  if(!is.null(comparison_post) & is.null(comparison_pre)) comparison_pre <- rep("", nrow(data))

  # Check if interactive
  if(!interactive()) stop("'handcode()' can only be run in an interactive R session.")


  # Initialize -------------------------------------------------------------------

  a <- data_for_app(data, start, randomize, context, pre, post, comparison_pre, comparison_post)

  # Run App ----------------------------------------------------------------------

  ret <- runApp(handcoder_app(a))

  # If pre and post given, attach to ret
  if(!is.null(pre) & !is.null(post)) {
    ret$pre <- pre
    ret$post <- post
  }

  # If comparison_pre and comparison_post given, attach to ret
  if(!is.null(comparison_pre) & !is.null(comparison_post)) {
    ret$comparison_pre <- comparison_pre
    ret$comparison_post <- comparison_post
  }

  # Output results ----------------------------------------------------------

  message("Please cite: Isermann, Lukas. 2023. handcodeR: Text annotation app. R package version 0.1.2. https://github.com/liserman/handcodeR")

  return(ret)

}




