name: Upload coverage reports to Codecov
on:
  push:
    branches:
      - master

jobs:
  upload:
    runs-on: ubuntu-20.04
    steps:
      - name: Upload to codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
